### ISSUE TITLE
Container Padding

### ISSUE THREAD

**Issue by JBraunsmaJr** [willj4945/Portfolio#1]
The text-based contents on the DOM are touching the edges of the screen. Thus, making it unreadable. 

Can apply some CSS padding to fix this.

Ideally, this CSS should be applied to 1 element and impact all children elements. 

Note: if you use re-usable classes in CSS you can apply similar logic to other things when needed.

For instance, 

```css
.p-2 { padding: 10px; }
.p-3 { padding 20px; }
```

The number's don't match because there are usually a pattern of 1-10 or 1-12 where you have some sort of interval in which things increment. Important takeaway here is knowing that if you apply `p-2` to something you're ONLY updating the padding of something and nothing else. 

Similarly, if we apply that logic you'll see how CSS frameworks do color-based classes. Slap this on an element and poof! 
```css
.bg-info { background-color: cyan; }
.bg-danger { background-color: red; }
.bg-success { background-color: green; }
```
